/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

import { Route as rootRouteImport } from "./routes/__root"
import { Route as Char123LocaleChar125RouteRouteImport } from "./routes/{-$locale}.route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as Char123LocaleChar125IndexRouteImport } from "./routes/{-$locale}/index"
import { Route as Char123LocaleChar125authSignInRouteImport } from "./routes/{-$locale}/(auth)/sign-in"
import { Route as Char123LocaleChar125authRegisterRouteImport } from "./routes/{-$locale}/(auth)/register"
import { Route as Char123LocaleChar125appAuthenticatedRouteRouteImport } from "./routes/{-$locale}/(app)/_authenticated.route"
import { Route as Char123LocaleChar125appProductsIndexRouteImport } from "./routes/{-$locale}/(app)/products/index"
import { Route as Char123LocaleChar125appCollectionsIndexRouteImport } from "./routes/{-$locale}/(app)/collections/index"
import { Route as Char123LocaleChar125appCartIndexRouteImport } from "./routes/{-$locale}/(app)/cart/index"
import { Route as Char123LocaleChar125appProductsChar123ProductHandleChar125RouteImport } from "./routes/{-$locale}/(app)/products/{-$productHandle}"
import { Route as Char123LocaleChar125appNewsletterUnsubscribeRouteImport } from "./routes/{-$locale}/(app)/newsletter/unsubscribe"
import { Route as Char123LocaleChar125appCollectionsChar123CollectionHandleChar125RouteImport } from "./routes/{-$locale}/(app)/collections/{-$collectionHandle}"
import { Route as Char123LocaleChar125appAuthenticatedAccountIndexRouteImport } from "./routes/{-$locale}/(app)/_authenticated/account/index"
import { Route as Char123LocaleChar125appAuthenticatedCheckoutSummaryRouteImport } from "./routes/{-$locale}/(app)/_authenticated/checkout/summary"
import { Route as Char123LocaleChar125appAuthenticatedCheckoutShippingRouteImport } from "./routes/{-$locale}/(app)/_authenticated/checkout/shipping"
import { Route as Char123LocaleChar125appAuthenticatedCheckoutDetailsRouteImport } from "./routes/{-$locale}/(app)/_authenticated/checkout/details"
import { Route as Char123LocaleChar125appAuthenticatedCheckoutCustomerRouteImport } from "./routes/{-$locale}/(app)/_authenticated/checkout/customer"
import { Route as Char123LocaleChar125appAuthenticatedAccountPreferencesRouteImport } from "./routes/{-$locale}/(app)/_authenticated/account/preferences"
import { Route as Char123LocaleChar125appAuthenticatedAccountOrdersIndexRouteImport } from "./routes/{-$locale}/(app)/_authenticated/account/orders/index"
import { Route as Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRouteImport } from "./routes/{-$locale}/(app)/_authenticated/account/orders/$orderId"

const Char123LocaleChar125appRouteImport =
  createFileRoute("/{-$locale}/(app)")()

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: "/{-$locale}",
    path: "/{-$locale}",
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125appRoute = Char123LocaleChar125appRouteImport.update({
  id: "/(app)",
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authSignInRoute =
  Char123LocaleChar125authSignInRouteImport.update({
    id: "/(auth)/sign-in",
    path: "/sign-in",
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authRegisterRoute =
  Char123LocaleChar125authRegisterRouteImport.update({
    id: "/(auth)/register",
    path: "/register",
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedRouteRoute =
  Char123LocaleChar125appAuthenticatedRouteRouteImport.update({
    id: "/_authenticated",
    getParentRoute: () => Char123LocaleChar125appRoute,
  } as any)
const Char123LocaleChar125appProductsIndexRoute =
  Char123LocaleChar125appProductsIndexRouteImport.update({
    id: "/products/",
    path: "/products/",
    getParentRoute: () => Char123LocaleChar125appRoute,
  } as any)
const Char123LocaleChar125appCollectionsIndexRoute =
  Char123LocaleChar125appCollectionsIndexRouteImport.update({
    id: "/collections/",
    path: "/collections/",
    getParentRoute: () => Char123LocaleChar125appRoute,
  } as any)
const Char123LocaleChar125appCartIndexRoute =
  Char123LocaleChar125appCartIndexRouteImport.update({
    id: "/cart/",
    path: "/cart/",
    getParentRoute: () => Char123LocaleChar125appRoute,
  } as any)
const Char123LocaleChar125appProductsChar123ProductHandleChar125Route =
  Char123LocaleChar125appProductsChar123ProductHandleChar125RouteImport.update({
    id: "/products/{-$productHandle}",
    path: "/products/{-$productHandle}",
    getParentRoute: () => Char123LocaleChar125appRoute,
  } as any)
const Char123LocaleChar125appNewsletterUnsubscribeRoute =
  Char123LocaleChar125appNewsletterUnsubscribeRouteImport.update({
    id: "/newsletter/unsubscribe",
    path: "/newsletter/unsubscribe",
    getParentRoute: () => Char123LocaleChar125appRoute,
  } as any)
const Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route =
  Char123LocaleChar125appCollectionsChar123CollectionHandleChar125RouteImport.update(
    {
      id: "/collections/{-$collectionHandle}",
      path: "/collections/{-$collectionHandle}",
      getParentRoute: () => Char123LocaleChar125appRoute,
    } as any,
  )
const Char123LocaleChar125appAuthenticatedAccountIndexRoute =
  Char123LocaleChar125appAuthenticatedAccountIndexRouteImport.update({
    id: "/account/",
    path: "/account/",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute =
  Char123LocaleChar125appAuthenticatedCheckoutSummaryRouteImport.update({
    id: "/checkout/summary",
    path: "/checkout/summary",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedCheckoutShippingRoute =
  Char123LocaleChar125appAuthenticatedCheckoutShippingRouteImport.update({
    id: "/checkout/shipping",
    path: "/checkout/shipping",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute =
  Char123LocaleChar125appAuthenticatedCheckoutDetailsRouteImport.update({
    id: "/checkout/details",
    path: "/checkout/details",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute =
  Char123LocaleChar125appAuthenticatedCheckoutCustomerRouteImport.update({
    id: "/checkout/customer",
    path: "/checkout/customer",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedAccountPreferencesRoute =
  Char123LocaleChar125appAuthenticatedAccountPreferencesRouteImport.update({
    id: "/account/preferences",
    path: "/account/preferences",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute =
  Char123LocaleChar125appAuthenticatedAccountOrdersIndexRouteImport.update({
    id: "/account/orders/",
    path: "/account/orders/",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute =
  Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRouteImport.update({
    id: "/account/orders/$orderId",
    path: "/account/orders/$orderId",
    getParentRoute: () => Char123LocaleChar125appAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/{-$locale}": typeof Char123LocaleChar125RouteRouteWithChildren
  "/{-$locale}/": typeof Char123LocaleChar125appAuthenticatedRouteRouteWithChildren
  "/{-$locale}/register": typeof Char123LocaleChar125authRegisterRoute
  "/{-$locale}/sign-in": typeof Char123LocaleChar125authSignInRoute
  "/{-$locale}/collections/{-$collectionHandle}": typeof Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route
  "/{-$locale}/newsletter/unsubscribe": typeof Char123LocaleChar125appNewsletterUnsubscribeRoute
  "/{-$locale}/products/{-$productHandle}": typeof Char123LocaleChar125appProductsChar123ProductHandleChar125Route
  "/{-$locale}/cart": typeof Char123LocaleChar125appCartIndexRoute
  "/{-$locale}/collections": typeof Char123LocaleChar125appCollectionsIndexRoute
  "/{-$locale}/products": typeof Char123LocaleChar125appProductsIndexRoute
  "/{-$locale}/account/preferences": typeof Char123LocaleChar125appAuthenticatedAccountPreferencesRoute
  "/{-$locale}/checkout/customer": typeof Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute
  "/{-$locale}/checkout/details": typeof Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute
  "/{-$locale}/checkout/shipping": typeof Char123LocaleChar125appAuthenticatedCheckoutShippingRoute
  "/{-$locale}/checkout/summary": typeof Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute
  "/{-$locale}/account": typeof Char123LocaleChar125appAuthenticatedAccountIndexRoute
  "/{-$locale}/account/orders/$orderId": typeof Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute
  "/{-$locale}/account/orders": typeof Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/{-$locale}": typeof Char123LocaleChar125appAuthenticatedRouteRouteWithChildren
  "/{-$locale}/register": typeof Char123LocaleChar125authRegisterRoute
  "/{-$locale}/sign-in": typeof Char123LocaleChar125authSignInRoute
  "/{-$locale}/collections/{-$collectionHandle}": typeof Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route
  "/{-$locale}/newsletter/unsubscribe": typeof Char123LocaleChar125appNewsletterUnsubscribeRoute
  "/{-$locale}/products/{-$productHandle}": typeof Char123LocaleChar125appProductsChar123ProductHandleChar125Route
  "/{-$locale}/cart": typeof Char123LocaleChar125appCartIndexRoute
  "/{-$locale}/collections": typeof Char123LocaleChar125appCollectionsIndexRoute
  "/{-$locale}/products": typeof Char123LocaleChar125appProductsIndexRoute
  "/{-$locale}/account/preferences": typeof Char123LocaleChar125appAuthenticatedAccountPreferencesRoute
  "/{-$locale}/checkout/customer": typeof Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute
  "/{-$locale}/checkout/details": typeof Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute
  "/{-$locale}/checkout/shipping": typeof Char123LocaleChar125appAuthenticatedCheckoutShippingRoute
  "/{-$locale}/checkout/summary": typeof Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute
  "/{-$locale}/account": typeof Char123LocaleChar125appAuthenticatedAccountIndexRoute
  "/{-$locale}/account/orders/$orderId": typeof Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute
  "/{-$locale}/account/orders": typeof Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/{-$locale}": typeof Char123LocaleChar125RouteRouteWithChildren
  "/{-$locale}/": typeof Char123LocaleChar125IndexRoute
  "/{-$locale}/(app)": typeof Char123LocaleChar125appRouteWithChildren
  "/{-$locale}/(app)/_authenticated": typeof Char123LocaleChar125appAuthenticatedRouteRouteWithChildren
  "/{-$locale}/(auth)/register": typeof Char123LocaleChar125authRegisterRoute
  "/{-$locale}/(auth)/sign-in": typeof Char123LocaleChar125authSignInRoute
  "/{-$locale}/(app)/collections/{-$collectionHandle}": typeof Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route
  "/{-$locale}/(app)/newsletter/unsubscribe": typeof Char123LocaleChar125appNewsletterUnsubscribeRoute
  "/{-$locale}/(app)/products/{-$productHandle}": typeof Char123LocaleChar125appProductsChar123ProductHandleChar125Route
  "/{-$locale}/(app)/cart/": typeof Char123LocaleChar125appCartIndexRoute
  "/{-$locale}/(app)/collections/": typeof Char123LocaleChar125appCollectionsIndexRoute
  "/{-$locale}/(app)/products/": typeof Char123LocaleChar125appProductsIndexRoute
  "/{-$locale}/(app)/_authenticated/account/preferences": typeof Char123LocaleChar125appAuthenticatedAccountPreferencesRoute
  "/{-$locale}/(app)/_authenticated/checkout/customer": typeof Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute
  "/{-$locale}/(app)/_authenticated/checkout/details": typeof Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute
  "/{-$locale}/(app)/_authenticated/checkout/shipping": typeof Char123LocaleChar125appAuthenticatedCheckoutShippingRoute
  "/{-$locale}/(app)/_authenticated/checkout/summary": typeof Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute
  "/{-$locale}/(app)/_authenticated/account/": typeof Char123LocaleChar125appAuthenticatedAccountIndexRoute
  "/{-$locale}/(app)/_authenticated/account/orders/$orderId": typeof Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute
  "/{-$locale}/(app)/_authenticated/account/orders/": typeof Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/{-$locale}"
    | "/{-$locale}/"
    | "/{-$locale}/register"
    | "/{-$locale}/sign-in"
    | "/{-$locale}/collections/{-$collectionHandle}"
    | "/{-$locale}/newsletter/unsubscribe"
    | "/{-$locale}/products/{-$productHandle}"
    | "/{-$locale}/cart"
    | "/{-$locale}/collections"
    | "/{-$locale}/products"
    | "/{-$locale}/account/preferences"
    | "/{-$locale}/checkout/customer"
    | "/{-$locale}/checkout/details"
    | "/{-$locale}/checkout/shipping"
    | "/{-$locale}/checkout/summary"
    | "/{-$locale}/account"
    | "/{-$locale}/account/orders/$orderId"
    | "/{-$locale}/account/orders"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/{-$locale}"
    | "/{-$locale}/register"
    | "/{-$locale}/sign-in"
    | "/{-$locale}/collections/{-$collectionHandle}"
    | "/{-$locale}/newsletter/unsubscribe"
    | "/{-$locale}/products/{-$productHandle}"
    | "/{-$locale}/cart"
    | "/{-$locale}/collections"
    | "/{-$locale}/products"
    | "/{-$locale}/account/preferences"
    | "/{-$locale}/checkout/customer"
    | "/{-$locale}/checkout/details"
    | "/{-$locale}/checkout/shipping"
    | "/{-$locale}/checkout/summary"
    | "/{-$locale}/account"
    | "/{-$locale}/account/orders/$orderId"
    | "/{-$locale}/account/orders"
  id:
    | "__root__"
    | "/"
    | "/{-$locale}"
    | "/{-$locale}/"
    | "/{-$locale}/(app)"
    | "/{-$locale}/(app)/_authenticated"
    | "/{-$locale}/(auth)/register"
    | "/{-$locale}/(auth)/sign-in"
    | "/{-$locale}/(app)/collections/{-$collectionHandle}"
    | "/{-$locale}/(app)/newsletter/unsubscribe"
    | "/{-$locale}/(app)/products/{-$productHandle}"
    | "/{-$locale}/(app)/cart/"
    | "/{-$locale}/(app)/collections/"
    | "/{-$locale}/(app)/products/"
    | "/{-$locale}/(app)/_authenticated/account/preferences"
    | "/{-$locale}/(app)/_authenticated/checkout/customer"
    | "/{-$locale}/(app)/_authenticated/checkout/details"
    | "/{-$locale}/(app)/_authenticated/checkout/shipping"
    | "/{-$locale}/(app)/_authenticated/checkout/summary"
    | "/{-$locale}/(app)/_authenticated/account/"
    | "/{-$locale}/(app)/_authenticated/account/orders/$orderId"
    | "/{-$locale}/(app)/_authenticated/account/orders/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/{-$locale}": {
      id: "/{-$locale}"
      path: "/{-$locale}"
      fullPath: "/{-$locale}"
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/{-$locale}/(app)": {
      id: "/{-$locale}/(app)"
      path: "/"
      fullPath: "/{-$locale}/"
      preLoaderRoute: typeof Char123LocaleChar125appRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    "/{-$locale}/": {
      id: "/{-$locale}/"
      path: "/"
      fullPath: "/{-$locale}/"
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    "/{-$locale}/(auth)/sign-in": {
      id: "/{-$locale}/(auth)/sign-in"
      path: "/sign-in"
      fullPath: "/{-$locale}/sign-in"
      preLoaderRoute: typeof Char123LocaleChar125authSignInRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    "/{-$locale}/(auth)/register": {
      id: "/{-$locale}/(auth)/register"
      path: "/register"
      fullPath: "/{-$locale}/register"
      preLoaderRoute: typeof Char123LocaleChar125authRegisterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    "/{-$locale}/(app)/_authenticated": {
      id: "/{-$locale}/(app)/_authenticated"
      path: "/"
      fullPath: "/{-$locale}/"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedRouteRouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/products/": {
      id: "/{-$locale}/(app)/products/"
      path: "/products"
      fullPath: "/{-$locale}/products"
      preLoaderRoute: typeof Char123LocaleChar125appProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/collections/": {
      id: "/{-$locale}/(app)/collections/"
      path: "/collections"
      fullPath: "/{-$locale}/collections"
      preLoaderRoute: typeof Char123LocaleChar125appCollectionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/cart/": {
      id: "/{-$locale}/(app)/cart/"
      path: "/cart"
      fullPath: "/{-$locale}/cart"
      preLoaderRoute: typeof Char123LocaleChar125appCartIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/products/{-$productHandle}": {
      id: "/{-$locale}/(app)/products/{-$productHandle}"
      path: "/products/{-$productHandle}"
      fullPath: "/{-$locale}/products/{-$productHandle}"
      preLoaderRoute: typeof Char123LocaleChar125appProductsChar123ProductHandleChar125RouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/newsletter/unsubscribe": {
      id: "/{-$locale}/(app)/newsletter/unsubscribe"
      path: "/newsletter/unsubscribe"
      fullPath: "/{-$locale}/newsletter/unsubscribe"
      preLoaderRoute: typeof Char123LocaleChar125appNewsletterUnsubscribeRouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/collections/{-$collectionHandle}": {
      id: "/{-$locale}/(app)/collections/{-$collectionHandle}"
      path: "/collections/{-$collectionHandle}"
      fullPath: "/{-$locale}/collections/{-$collectionHandle}"
      preLoaderRoute: typeof Char123LocaleChar125appCollectionsChar123CollectionHandleChar125RouteImport
      parentRoute: typeof Char123LocaleChar125appRoute
    }
    "/{-$locale}/(app)/_authenticated/account/": {
      id: "/{-$locale}/(app)/_authenticated/account/"
      path: "/account"
      fullPath: "/{-$locale}/account"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedAccountIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/checkout/summary": {
      id: "/{-$locale}/(app)/_authenticated/checkout/summary"
      path: "/checkout/summary"
      fullPath: "/{-$locale}/checkout/summary"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutSummaryRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/checkout/shipping": {
      id: "/{-$locale}/(app)/_authenticated/checkout/shipping"
      path: "/checkout/shipping"
      fullPath: "/{-$locale}/checkout/shipping"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutShippingRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/checkout/details": {
      id: "/{-$locale}/(app)/_authenticated/checkout/details"
      path: "/checkout/details"
      fullPath: "/{-$locale}/checkout/details"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutDetailsRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/checkout/customer": {
      id: "/{-$locale}/(app)/_authenticated/checkout/customer"
      path: "/checkout/customer"
      fullPath: "/{-$locale}/checkout/customer"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutCustomerRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/account/preferences": {
      id: "/{-$locale}/(app)/_authenticated/account/preferences"
      path: "/account/preferences"
      fullPath: "/{-$locale}/account/preferences"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedAccountPreferencesRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/account/orders/": {
      id: "/{-$locale}/(app)/_authenticated/account/orders/"
      path: "/account/orders"
      fullPath: "/{-$locale}/account/orders"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedAccountOrdersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
    "/{-$locale}/(app)/_authenticated/account/orders/$orderId": {
      id: "/{-$locale}/(app)/_authenticated/account/orders/$orderId"
      path: "/account/orders/$orderId"
      fullPath: "/{-$locale}/account/orders/$orderId"
      preLoaderRoute: typeof Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRouteImport
      parentRoute: typeof Char123LocaleChar125appAuthenticatedRouteRoute
    }
  }
}

interface Char123LocaleChar125appAuthenticatedRouteRouteChildren {
  Char123LocaleChar125appAuthenticatedAccountPreferencesRoute: typeof Char123LocaleChar125appAuthenticatedAccountPreferencesRoute
  Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute
  Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute
  Char123LocaleChar125appAuthenticatedCheckoutShippingRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutShippingRoute
  Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute: typeof Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute
  Char123LocaleChar125appAuthenticatedAccountIndexRoute: typeof Char123LocaleChar125appAuthenticatedAccountIndexRoute
  Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute: typeof Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute
  Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute: typeof Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute
}

const Char123LocaleChar125appAuthenticatedRouteRouteChildren: Char123LocaleChar125appAuthenticatedRouteRouteChildren =
  {
    Char123LocaleChar125appAuthenticatedAccountPreferencesRoute:
      Char123LocaleChar125appAuthenticatedAccountPreferencesRoute,
    Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute:
      Char123LocaleChar125appAuthenticatedCheckoutCustomerRoute,
    Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute:
      Char123LocaleChar125appAuthenticatedCheckoutDetailsRoute,
    Char123LocaleChar125appAuthenticatedCheckoutShippingRoute:
      Char123LocaleChar125appAuthenticatedCheckoutShippingRoute,
    Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute:
      Char123LocaleChar125appAuthenticatedCheckoutSummaryRoute,
    Char123LocaleChar125appAuthenticatedAccountIndexRoute:
      Char123LocaleChar125appAuthenticatedAccountIndexRoute,
    Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute:
      Char123LocaleChar125appAuthenticatedAccountOrdersOrderIdRoute,
    Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute:
      Char123LocaleChar125appAuthenticatedAccountOrdersIndexRoute,
  }

const Char123LocaleChar125appAuthenticatedRouteRouteWithChildren =
  Char123LocaleChar125appAuthenticatedRouteRoute._addFileChildren(
    Char123LocaleChar125appAuthenticatedRouteRouteChildren,
  )

interface Char123LocaleChar125appRouteChildren {
  Char123LocaleChar125appAuthenticatedRouteRoute: typeof Char123LocaleChar125appAuthenticatedRouteRouteWithChildren
  Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route: typeof Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route
  Char123LocaleChar125appNewsletterUnsubscribeRoute: typeof Char123LocaleChar125appNewsletterUnsubscribeRoute
  Char123LocaleChar125appProductsChar123ProductHandleChar125Route: typeof Char123LocaleChar125appProductsChar123ProductHandleChar125Route
  Char123LocaleChar125appCartIndexRoute: typeof Char123LocaleChar125appCartIndexRoute
  Char123LocaleChar125appCollectionsIndexRoute: typeof Char123LocaleChar125appCollectionsIndexRoute
  Char123LocaleChar125appProductsIndexRoute: typeof Char123LocaleChar125appProductsIndexRoute
}

const Char123LocaleChar125appRouteChildren: Char123LocaleChar125appRouteChildren =
  {
    Char123LocaleChar125appAuthenticatedRouteRoute:
      Char123LocaleChar125appAuthenticatedRouteRouteWithChildren,
    Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route:
      Char123LocaleChar125appCollectionsChar123CollectionHandleChar125Route,
    Char123LocaleChar125appNewsletterUnsubscribeRoute:
      Char123LocaleChar125appNewsletterUnsubscribeRoute,
    Char123LocaleChar125appProductsChar123ProductHandleChar125Route:
      Char123LocaleChar125appProductsChar123ProductHandleChar125Route,
    Char123LocaleChar125appCartIndexRoute:
      Char123LocaleChar125appCartIndexRoute,
    Char123LocaleChar125appCollectionsIndexRoute:
      Char123LocaleChar125appCollectionsIndexRoute,
    Char123LocaleChar125appProductsIndexRoute:
      Char123LocaleChar125appProductsIndexRoute,
  }

const Char123LocaleChar125appRouteWithChildren =
  Char123LocaleChar125appRoute._addFileChildren(
    Char123LocaleChar125appRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125appRoute: typeof Char123LocaleChar125appRouteWithChildren
  Char123LocaleChar125authRegisterRoute: typeof Char123LocaleChar125authRegisterRoute
  Char123LocaleChar125authSignInRoute: typeof Char123LocaleChar125authSignInRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125appRoute: Char123LocaleChar125appRouteWithChildren,
    Char123LocaleChar125authRegisterRoute:
      Char123LocaleChar125authRegisterRoute,
    Char123LocaleChar125authSignInRoute: Char123LocaleChar125authSignInRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
